// <auto-generated />
using Food_project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Food_project.Migrations
{
    [DbContext(typeof(FoodContext))]
    [Migration("20240514142042_mygration")]
    partial class mygration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.3.24172.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Food_project.Models.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbtv-UwXqSWD55s_nAdxP7Wofwn3by_lhhQoXPff7O9g&s",
                            Name = "Pizza",
                            price = 1000.0
                        });
                });

            modelBuilder.Entity("Food_project.Models.Dishingrediant", b =>
                {
                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("IngregiantId")
                        .HasColumnType("int");

                    b.HasKey("DishId", "IngregiantId");

                    b.HasIndex("IngregiantId");

                    b.ToTable("Dishingrediants");

                    b.HasData(
                        new
                        {
                            DishId = 1,
                            IngregiantId = 1
                        },
                        new
                        {
                            DishId = 1,
                            IngregiantId = 2
                        });
                });

            modelBuilder.Entity("Food_project.Models.Ingrediant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingrediants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mozeralla"
                        },
                        new
                        {
                            Id = 2,
                            Name = "prawns"
                        });
                });

            modelBuilder.Entity("Food_project.Models.Dishingrediant", b =>
                {
                    b.HasOne("Food_project.Models.Dish", "Dish")
                        .WithMany("Dishingrediants")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Food_project.Models.Ingrediant", "Ingrediant")
                        .WithMany("Dishingrediants")
                        .HasForeignKey("IngregiantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Ingrediant");
                });

            modelBuilder.Entity("Food_project.Models.Dish", b =>
                {
                    b.Navigation("Dishingrediants");
                });

            modelBuilder.Entity("Food_project.Models.Ingrediant", b =>
                {
                    b.Navigation("Dishingrediants");
                });
#pragma warning restore 612, 618
        }
    }
}
